FROM gradle:9.2.1-jdk21 AS builder

WORKDIR /app

LABEL authors="Aerodream"

COPY document-generator/build/libs/*.jar app.jar

EXPOSE 8081

ENV SPRING_PROFILES_ACTIVE=docker

ENTRYPOINT ["java", "-jar", "app.jar"]